/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  DeterminationContract,
  DeterminationContractInterface,
} from "../DeterminationContract";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "targetSubgraphDataset",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "currentSubgraphDataset",
        type: "uint256[]",
      },
    ],
    name: "calculation",
    outputs: [
      {
        internalType: "bool",
        name: "determination",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610299806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063b74698dc14610030575b600080fd5b61004361003e366004610176565b610057565b604051901515815260200160405180910390f35b60008381805b8281101561009d57878782818110610077576100776101e2565b9050602002013582610089919061020e565b91508061009581610226565b91505061005d565b5060006100aa8383610241565b9050846000805b828110156100f1578888828181106100cb576100cb6101e2565b90506020020135826100dd919061020e565b9150806100e981610226565b9150506100b1565b5060006100fe8383610241565b9050808411156101175760019650505050505050610122565b600096505050505050505b949350505050565b60008083601f84011261013c57600080fd5b50813567ffffffffffffffff81111561015457600080fd5b6020830191508360208260051b850101111561016f57600080fd5b9250929050565b6000806000806040858703121561018c57600080fd5b843567ffffffffffffffff808211156101a457600080fd5b6101b08883890161012a565b909650945060208701359150808211156101c957600080fd5b506101d68782880161012a565b95989497509550505050565b634e487b7160e01b600052603260045260246000fd5b634e487b7160e01b600052601160045260246000fd5b60008219821115610221576102216101f8565b500190565b600060001982141561023a5761023a6101f8565b5060010190565b60008261025e57634e487b7160e01b600052601260045260246000fd5b50049056fea26469706673582212205c00f4c8c57068aaa67494f8c1fbe38447f699dd8eb37a4a006ebf05762743e364736f6c63430008090033";

type DeterminationContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DeterminationContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DeterminationContract__factory extends ContractFactory {
  constructor(...args: DeterminationContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "DeterminationContract";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DeterminationContract> {
    return super.deploy(overrides || {}) as Promise<DeterminationContract>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DeterminationContract {
    return super.attach(address) as DeterminationContract;
  }
  connect(signer: Signer): DeterminationContract__factory {
    return super.connect(signer) as DeterminationContract__factory;
  }
  static readonly contractName: "DeterminationContract";
  public readonly contractName: "DeterminationContract";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DeterminationContractInterface {
    return new utils.Interface(_abi) as DeterminationContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DeterminationContract {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DeterminationContract;
  }
}
