/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { GovContract, GovContractInterface } from "../GovContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "support",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "castVoteWithReason",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class GovContract__factory {
  static readonly abi = _abi;
  static createInterface(): GovContractInterface {
    return new utils.Interface(_abi) as GovContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GovContract {
    return new Contract(address, _abi, signerOrProvider) as GovContract;
  }
}
