/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGovernorContract,
  IGovernorContractInterface,
} from "../IGovernorContract";

const _abi = [
  {
    inputs: [],
    name: "timelock",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGovernorContract__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernorContractInterface {
    return new utils.Interface(_abi) as IGovernorContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGovernorContract {
    return new Contract(address, _abi, signerOrProvider) as IGovernorContract;
  }
}
