/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPoolManagerStandard,
  IPoolManagerStandardInterface,
} from "../IPoolManagerStandard";

const _abi = [
  {
    inputs: [],
    name: "reserveContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "setReserveContractAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "title",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPoolManagerStandard__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolManagerStandardInterface {
    return new utils.Interface(_abi) as IPoolManagerStandardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolManagerStandard {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPoolManagerStandard;
  }
}
