/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IProtocolReserveManager,
  IProtocolReserveManagerInterface,
} from "../IProtocolReserveManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "acctProtocolRevenueCalculation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IProtocolReserveManager__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolReserveManagerInterface {
    return new utils.Interface(_abi) as IProtocolReserveManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProtocolReserveManager {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IProtocolReserveManager;
  }
}
