/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface DeterminationContractInterface extends utils.Interface {
  contractName: "DeterminationContract";
  functions: {
    "calculation(uint256[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculation",
    values: [BigNumberish[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculation",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DeterminationContract extends BaseContract {
  contractName: "DeterminationContract";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeterminationContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    calculation(
      targetSubgraphDataset: BigNumberish[],
      currentSubgraphDataset: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[boolean] & { determination: boolean }>;
  };

  calculation(
    targetSubgraphDataset: BigNumberish[],
    currentSubgraphDataset: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    calculation(
      targetSubgraphDataset: BigNumberish[],
      currentSubgraphDataset: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    calculation(
      targetSubgraphDataset: BigNumberish[],
      currentSubgraphDataset: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculation(
      targetSubgraphDataset: BigNumberish[],
      currentSubgraphDataset: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
