/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ProtocolReserveManagerInterface extends utils.Interface {
  contractName: "ProtocolReserveManager";
  functions: {
    "_isContract(address)": FunctionFragment;
    "addSubgraph(address)": FunctionFragment;
    "cummulativeReserveFactor(uint256)": FunctionFragment;
    "deployPoolContract(address,bytes32,uint256,address,bytes32)": FunctionFragment;
    "displayPoolList()": FunctionFragment;
    "displaySubgraphList()": FunctionFragment;
    "findSwapPool(address)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "originalDeployer()": FunctionFragment;
    "protocolRevenueCalculation(address)": FunctionFragment;
    "protocolToken()": FunctionFragment;
    "revenueAvailableByUser(address)": FunctionFragment;
    "titleToPool(bytes32)": FunctionFragment;
    "transferRevenueAsWETH(address,uint256)": FunctionFragment;
    "uniswapPoolCache(address)": FunctionFragment;
    "updateProtocolRevenueFactor(uint256)": FunctionFragment;
    "userToLastUpdateNonce(address)": FunctionFragment;
    "viewProtocolLevelRevenue(address)": FunctionFragment;
    "withdrawRevenues(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "_isContract", values: [string]): string;
  encodeFunctionData(functionFragment: "addSubgraph", values: [string]): string;
  encodeFunctionData(
    functionFragment: "cummulativeReserveFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployPoolContract",
    values: [string, BytesLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "displayPoolList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "displaySubgraphList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "findSwapPool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "originalDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolRevenueCalculation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revenueAvailableByUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "titleToPool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRevenueAsWETH",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapPoolCache",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProtocolRevenueFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userToLastUpdateNonce",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "viewProtocolLevelRevenue",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRevenues",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "_isContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSubgraph",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cummulativeReserveFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployPoolContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "displayPoolList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "displaySubgraphList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findSwapPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "originalDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolRevenueCalculation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revenueAvailableByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "titleToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRevenueAsWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapPoolCache",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProtocolRevenueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userToLastUpdateNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewProtocolLevelRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRevenues",
    data: BytesLike
  ): Result;

  events: {
    "PoolContractDeployed(address)": EventFragment;
    "TokensWithdrawn(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PoolContractDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensWithdrawn"): EventFragment;
}

export type PoolContractDeployedEvent = TypedEvent<
  [string],
  { contractAddress: string }
>;

export type PoolContractDeployedEventFilter =
  TypedEventFilter<PoolContractDeployedEvent>;

export type TokensWithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  { token: string; recipient: string; amount: BigNumber }
>;

export type TokensWithdrawnEventFilter = TypedEventFilter<TokensWithdrawnEvent>;

export interface ProtocolReserveManager extends BaseContract {
  contractName: "ProtocolReserveManager";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProtocolReserveManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _isContract(
      _a: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addSubgraph(
      subgraphAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cummulativeReserveFactor(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deployPoolContract(
      depositToken: string,
      title: BytesLike,
      initialDepositAmount: BigNumberish,
      subgraphPivotTarget: string,
      poolIdPivotTarget: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    displayPoolList(overrides?: CallOverrides): Promise<[string[]]>;

    displaySubgraphList(overrides?: CallOverrides): Promise<[string[]]>;

    findSwapPool(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      tokenAddress: string,
      governorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    originalDeployer(overrides?: CallOverrides): Promise<[string]>;

    protocolRevenueCalculation(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    protocolToken(overrides?: CallOverrides): Promise<[string]>;

    revenueAvailableByUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    titleToPool(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    transferRevenueAsWETH(
      revenueToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniswapPoolCache(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    updateProtocolRevenueFactor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userToLastUpdateNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    viewProtocolLevelRevenue(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { availableRevenue: BigNumber }>;

    withdrawRevenues(
      amount: BigNumberish,
      revenueToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _isContract(
    _a: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addSubgraph(
    subgraphAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cummulativeReserveFactor(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deployPoolContract(
    depositToken: string,
    title: BytesLike,
    initialDepositAmount: BigNumberish,
    subgraphPivotTarget: string,
    poolIdPivotTarget: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  displayPoolList(overrides?: CallOverrides): Promise<string[]>;

  displaySubgraphList(overrides?: CallOverrides): Promise<string[]>;

  findSwapPool(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    tokenAddress: string,
    governorAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  originalDeployer(overrides?: CallOverrides): Promise<string>;

  protocolRevenueCalculation(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  protocolToken(overrides?: CallOverrides): Promise<string>;

  revenueAvailableByUser(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  titleToPool(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  transferRevenueAsWETH(
    revenueToken: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniswapPoolCache(arg0: string, overrides?: CallOverrides): Promise<string>;

  updateProtocolRevenueFactor(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userToLastUpdateNonce(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  viewProtocolLevelRevenue(
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawRevenues(
    amount: BigNumberish,
    revenueToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _isContract(_a: string, overrides?: CallOverrides): Promise<boolean>;

    addSubgraph(
      subgraphAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    cummulativeReserveFactor(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployPoolContract(
      depositToken: string,
      title: BytesLike,
      initialDepositAmount: BigNumberish,
      subgraphPivotTarget: string,
      poolIdPivotTarget: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    displayPoolList(overrides?: CallOverrides): Promise<string[]>;

    displaySubgraphList(overrides?: CallOverrides): Promise<string[]>;

    findSwapPool(token: string, overrides?: CallOverrides): Promise<string>;

    initialize(
      tokenAddress: string,
      governorAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    originalDeployer(overrides?: CallOverrides): Promise<string>;

    protocolRevenueCalculation(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    protocolToken(overrides?: CallOverrides): Promise<string>;

    revenueAvailableByUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    titleToPool(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    transferRevenueAsWETH(
      revenueToken: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    uniswapPoolCache(arg0: string, overrides?: CallOverrides): Promise<string>;

    updateProtocolRevenueFactor(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    userToLastUpdateNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewProtocolLevelRevenue(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawRevenues(
      amount: BigNumberish,
      revenueToken: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "PoolContractDeployed(address)"(
      contractAddress?: null
    ): PoolContractDeployedEventFilter;
    PoolContractDeployed(
      contractAddress?: null
    ): PoolContractDeployedEventFilter;

    "TokensWithdrawn(address,address,uint256)"(
      token?: string | null,
      recipient?: string | null,
      amount?: null
    ): TokensWithdrawnEventFilter;
    TokensWithdrawn(
      token?: string | null,
      recipient?: string | null,
      amount?: null
    ): TokensWithdrawnEventFilter;
  };

  estimateGas: {
    _isContract(
      _a: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addSubgraph(
      subgraphAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cummulativeReserveFactor(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployPoolContract(
      depositToken: string,
      title: BytesLike,
      initialDepositAmount: BigNumberish,
      subgraphPivotTarget: string,
      poolIdPivotTarget: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    displayPoolList(overrides?: CallOverrides): Promise<BigNumber>;

    displaySubgraphList(overrides?: CallOverrides): Promise<BigNumber>;

    findSwapPool(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      tokenAddress: string,
      governorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    originalDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    protocolRevenueCalculation(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    protocolToken(overrides?: CallOverrides): Promise<BigNumber>;

    revenueAvailableByUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    titleToPool(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    transferRevenueAsWETH(
      revenueToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniswapPoolCache(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateProtocolRevenueFactor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userToLastUpdateNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewProtocolLevelRevenue(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawRevenues(
      amount: BigNumberish,
      revenueToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _isContract(
      _a: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addSubgraph(
      subgraphAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cummulativeReserveFactor(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployPoolContract(
      depositToken: string,
      title: BytesLike,
      initialDepositAmount: BigNumberish,
      subgraphPivotTarget: string,
      poolIdPivotTarget: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    displayPoolList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    displaySubgraphList(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    findSwapPool(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      tokenAddress: string,
      governorAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    originalDeployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolRevenueCalculation(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    protocolToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revenueAvailableByUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    titleToPool(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferRevenueAsWETH(
      revenueToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniswapPoolCache(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateProtocolRevenueFactor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userToLastUpdateNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewProtocolLevelRevenue(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawRevenues(
      amount: BigNumberish,
      revenueToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
