/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ProtocolReserveManagerInterface extends utils.Interface {
  contractName: "ProtocolReserveManager";
  functions: {
    "_isContract(address)": FunctionFragment;
    "acctProtocolRevenueCalculation(address)": FunctionFragment;
    "cummulativeReserveFactor(uint256)": FunctionFragment;
    "deployPoolContract(address,bytes32,uint256,address,bytes32)": FunctionFragment;
    "deployTestToken()": FunctionFragment;
    "findSwapPool(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "protocolToken()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revenueAvailableByUser(address)": FunctionFragment;
    "titleToPool(bytes32)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferRevenueAsWETH(address,address,uint256)": FunctionFragment;
    "uniswapPoolCache(address)": FunctionFragment;
    "updateProtocolRevenueFactor(uint256)": FunctionFragment;
    "userToLastUpdateNonce(address)": FunctionFragment;
    "withdrawRevenues(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "_isContract", values: [string]): string;
  encodeFunctionData(
    functionFragment: "acctProtocolRevenueCalculation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "cummulativeReserveFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployPoolContract",
    values: [string, BytesLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployTestToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "findSwapPool",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revenueAvailableByUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "titleToPool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRevenueAsWETH",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapPoolCache",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProtocolRevenueFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userToLastUpdateNonce",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRevenues",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "_isContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acctProtocolRevenueCalculation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cummulativeReserveFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployPoolContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployTestToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findSwapPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revenueAvailableByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "titleToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRevenueAsWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapPoolCache",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProtocolRevenueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userToLastUpdateNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRevenues",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "PoolContractDeployed(address)": EventFragment;
    "TestTokenDeployed(address)": EventFragment;
    "TokensWithdrawn(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolContractDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TestTokenDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensWithdrawn"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type PoolContractDeployedEvent = TypedEvent<
  [string],
  { contractAddress: string }
>;

export type PoolContractDeployedEventFilter =
  TypedEventFilter<PoolContractDeployedEvent>;

export type TestTokenDeployedEvent = TypedEvent<
  [string],
  { tokenAddress: string }
>;

export type TestTokenDeployedEventFilter =
  TypedEventFilter<TestTokenDeployedEvent>;

export type TokensWithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  { token: string; recipient: string; amount: BigNumber }
>;

export type TokensWithdrawnEventFilter = TypedEventFilter<TokensWithdrawnEvent>;

export interface ProtocolReserveManager extends BaseContract {
  contractName: "ProtocolReserveManager";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProtocolReserveManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _isContract(
      _a: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    acctProtocolRevenueCalculation(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cummulativeReserveFactor(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deployPoolContract(
      depositToken: string,
      title: BytesLike,
      initialDepositAmount: BigNumberish,
      subgraphPivotTarget: string,
      poolIdPivotTarget: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployTestToken(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    findSwapPool(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    protocolToken(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revenueAvailableByUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    titleToPool(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferRevenueAsWETH(
      pool: string,
      revenueToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniswapPoolCache(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    updateProtocolRevenueFactor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userToLastUpdateNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawRevenues(
      amount: BigNumberish,
      revenueToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _isContract(
    _a: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  acctProtocolRevenueCalculation(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cummulativeReserveFactor(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deployPoolContract(
    depositToken: string,
    title: BytesLike,
    initialDepositAmount: BigNumberish,
    subgraphPivotTarget: string,
    poolIdPivotTarget: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployTestToken(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  findSwapPool(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  protocolToken(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revenueAvailableByUser(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  titleToPool(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferRevenueAsWETH(
    pool: string,
    revenueToken: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniswapPoolCache(arg0: string, overrides?: CallOverrides): Promise<string>;

  updateProtocolRevenueFactor(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userToLastUpdateNonce(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawRevenues(
    amount: BigNumberish,
    revenueToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _isContract(_a: string, overrides?: CallOverrides): Promise<boolean>;

    acctProtocolRevenueCalculation(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cummulativeReserveFactor(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployPoolContract(
      depositToken: string,
      title: BytesLike,
      initialDepositAmount: BigNumberish,
      subgraphPivotTarget: string,
      poolIdPivotTarget: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    deployTestToken(overrides?: CallOverrides): Promise<void>;

    findSwapPool(token: string, overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    protocolToken(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revenueAvailableByUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    titleToPool(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferRevenueAsWETH(
      pool: string,
      revenueToken: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    uniswapPoolCache(arg0: string, overrides?: CallOverrides): Promise<string>;

    updateProtocolRevenueFactor(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    userToLastUpdateNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawRevenues(
      amount: BigNumberish,
      revenueToken: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PoolContractDeployed(address)"(
      contractAddress?: null
    ): PoolContractDeployedEventFilter;
    PoolContractDeployed(
      contractAddress?: null
    ): PoolContractDeployedEventFilter;

    "TestTokenDeployed(address)"(
      tokenAddress?: null
    ): TestTokenDeployedEventFilter;
    TestTokenDeployed(tokenAddress?: null): TestTokenDeployedEventFilter;

    "TokensWithdrawn(address,address,uint256)"(
      token?: string | null,
      recipient?: string | null,
      amount?: null
    ): TokensWithdrawnEventFilter;
    TokensWithdrawn(
      token?: string | null,
      recipient?: string | null,
      amount?: null
    ): TokensWithdrawnEventFilter;
  };

  estimateGas: {
    _isContract(
      _a: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    acctProtocolRevenueCalculation(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cummulativeReserveFactor(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployPoolContract(
      depositToken: string,
      title: BytesLike,
      initialDepositAmount: BigNumberish,
      subgraphPivotTarget: string,
      poolIdPivotTarget: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployTestToken(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    findSwapPool(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    protocolToken(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revenueAvailableByUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    titleToPool(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferRevenueAsWETH(
      pool: string,
      revenueToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniswapPoolCache(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateProtocolRevenueFactor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userToLastUpdateNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawRevenues(
      amount: BigNumberish,
      revenueToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _isContract(
      _a: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    acctProtocolRevenueCalculation(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cummulativeReserveFactor(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployPoolContract(
      depositToken: string,
      title: BytesLike,
      initialDepositAmount: BigNumberish,
      subgraphPivotTarget: string,
      poolIdPivotTarget: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployTestToken(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    findSwapPool(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revenueAvailableByUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    titleToPool(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferRevenueAsWETH(
      pool: string,
      revenueToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniswapPoolCache(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateProtocolRevenueFactor(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userToLastUpdateNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawRevenues(
      amount: BigNumberish,
      revenueToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
